environment:
  matrix:
    - BUILD_TYPE: Release
      PLATFORM: x86
      QT: 5.9\msvc2015

    - BUILD_TYPE: Release
      PLATFORM: x64
      QT: 5.9\msvc2015_64

    - BUILD_TYPE: Debug
      PLATFORM: x86
      QT: 5.9\msvc2015

    - BUILD_TYPE: Debug
      PLATFORM: x64
      QT: 5.9\msvc2015_64

init:
  - set PATH=C:\Qt\%QT%\bin;%PATH%

clone_folder: c:\dev\kdiff3

build_script:
  - md build
  - cd build
  - if [%PLATFORM%]==[x86] cmake ..\kdiff3 -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_WITH=qt5
  - if [%PLATFORM%]==[x64] cmake ..\kdiff3 -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_WITH=qt5
  - cmake --build . --config %BUILD_TYPE%
